// <auto-generated />
namespace ArtPainter
{
    partial class ShapeEditor
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.panelFillColor = new System.Windows.Forms.Panel();
            this.btnChangeFillColor = new System.Windows.Forms.Button();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.panelBorderColor = new System.Windows.Forms.Panel();
            this.btnChangeBorderColor = new System.Windows.Forms.Button();
            this.btnOK = new System.Windows.Forms.Button();
            this.cbMoveable = new System.Windows.Forms.CheckBox();
            this.numericRotation = new System.Windows.Forms.NumericUpDown();
            this.tbCenterPoint = new System.Windows.Forms.TextBox();
            this.pointPanel = new System.Windows.Forms.Panel();
            this.cbRotateable = new System.Windows.Forms.CheckBox();
            this.label1 = new System.Windows.Forms.Label();
            this.cbResizeable = new System.Windows.Forms.CheckBox();
            this.label2 = new System.Windows.Forms.Label();
            this.tbArea = new System.Windows.Forms.TextBox();
            this.btRandomize = new System.Windows.Forms.Button();
            this.btAddImage = new System.Windows.Forms.Button();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numericRotation)).BeginInit();
            this.SuspendLayout();
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.panelFillColor);
            this.groupBox1.Controls.Add(this.btnChangeFillColor);
            this.groupBox1.Location = new System.Drawing.Point(12, 12);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(200, 51);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Farbe";
            // 
            // panelFillColor
            // 
            this.panelFillColor.Location = new System.Drawing.Point(143, 19);
            this.panelFillColor.Name = "panelFillColor";
            this.panelFillColor.Size = new System.Drawing.Size(51, 23);
            this.panelFillColor.TabIndex = 6;
            // 
            // btnChangeFillColor
            // 
            this.btnChangeFillColor.Location = new System.Drawing.Point(6, 19);
            this.btnChangeFillColor.Name = "btnChangeFillColor";
            this.btnChangeFillColor.Size = new System.Drawing.Size(131, 23);
            this.btnChangeFillColor.TabIndex = 0;
            this.btnChangeFillColor.Text = "Farbe ändern";
            this.btnChangeFillColor.UseVisualStyleBackColor = true;
            this.btnChangeFillColor.Click += new System.EventHandler(this.ChangeFillColor_Click);
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.panelBorderColor);
            this.groupBox2.Controls.Add(this.btnChangeBorderColor);
            this.groupBox2.Location = new System.Drawing.Point(12, 69);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(200, 51);
            this.groupBox2.TabIndex = 1;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Rahmenfarbe";
            // 
            // panelBorderColor
            // 
            this.panelBorderColor.Location = new System.Drawing.Point(143, 19);
            this.panelBorderColor.Name = "panelBorderColor";
            this.panelBorderColor.Size = new System.Drawing.Size(51, 23);
            this.panelBorderColor.TabIndex = 7;
            // 
            // btnChangeBorderColor
            // 
            this.btnChangeBorderColor.Location = new System.Drawing.Point(6, 19);
            this.btnChangeBorderColor.Name = "btnChangeBorderColor";
            this.btnChangeBorderColor.Size = new System.Drawing.Size(131, 23);
            this.btnChangeBorderColor.TabIndex = 0;
            this.btnChangeBorderColor.Text = "Rahmenfarbe ändern";
            this.btnChangeBorderColor.UseVisualStyleBackColor = true;
            this.btnChangeBorderColor.Click += new System.EventHandler(this.ChangeBorderColor_Click);
            // 
            // btnOK
            // 
            this.btnOK.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnOK.Location = new System.Drawing.Point(467, 300);
            this.btnOK.Name = "btnOK";
            this.btnOK.Size = new System.Drawing.Size(75, 23);
            this.btnOK.TabIndex = 3;
            this.btnOK.Text = "OK";
            this.btnOK.UseVisualStyleBackColor = true;
            // 
            // cbMoveable
            // 
            this.cbMoveable.AutoSize = true;
            this.cbMoveable.Location = new System.Drawing.Point(12, 126);
            this.cbMoveable.Name = "cbMoveable";
            this.cbMoveable.Size = new System.Drawing.Size(88, 17);
            this.cbMoveable.TabIndex = 6;
            this.cbMoveable.Text = "Verschiebbar";
            this.cbMoveable.UseVisualStyleBackColor = true;
            this.cbMoveable.CheckedChanged += new System.EventHandler(this.Moveable_CheckedChanged);
            // 
            // numericRotation
            // 
            this.numericRotation.Location = new System.Drawing.Point(12, 205);
            this.numericRotation.Maximum = new decimal(new int[] {
            360,
            0,
            0,
            0});
            this.numericRotation.Name = "numericRotation";
            this.numericRotation.Size = new System.Drawing.Size(200, 20);
            this.numericRotation.TabIndex = 7;
            this.numericRotation.ValueChanged += new System.EventHandler(this.NumericRotation_ValueChanged);
            // 
            // tbCenterPoint
            // 
            this.tbCenterPoint.Enabled = false;
            this.tbCenterPoint.Location = new System.Drawing.Point(12, 249);
            this.tbCenterPoint.Name = "tbCenterPoint";
            this.tbCenterPoint.Size = new System.Drawing.Size(200, 20);
            this.tbCenterPoint.TabIndex = 8;
            // 
            // pointPanel
            // 
            this.pointPanel.AutoScroll = true;
            this.pointPanel.Location = new System.Drawing.Point(218, 11);
            this.pointPanel.Name = "pointPanel";
            this.pointPanel.Size = new System.Drawing.Size(324, 283);
            this.pointPanel.TabIndex = 9;
            // 
            // cbRotateable
            // 
            this.cbRotateable.AutoSize = true;
            this.cbRotateable.Location = new System.Drawing.Point(12, 149);
            this.cbRotateable.Name = "cbRotateable";
            this.cbRotateable.Size = new System.Drawing.Size(69, 17);
            this.cbRotateable.TabIndex = 10;
            this.cbRotateable.Text = "Rotierbar";
            this.cbRotateable.UseVisualStyleBackColor = true;
            this.cbRotateable.CheckedChanged += new System.EventHandler(this.Rotateable_CheckedChanged);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(15, 233);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(46, 13);
            this.label1.TabIndex = 11;
            this.label1.Text = "Zentrum";
            // 
            // cbResizeable
            // 
            this.cbResizeable.AutoSize = true;
            this.cbResizeable.Location = new System.Drawing.Point(12, 172);
            this.cbResizeable.Name = "cbResizeable";
            this.cbResizeable.Size = new System.Drawing.Size(164, 17);
            this.cbResizeable.TabIndex = 12;
            this.cbResizeable.Text = "Vergrösserbar / Verkleinerbar";
            this.cbResizeable.UseVisualStyleBackColor = true;
            this.cbResizeable.CheckedChanged += new System.EventHandler(this.Resizeable_CheckedChanged);
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(15, 272);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(39, 13);
            this.label2.TabIndex = 13;
            this.label2.Text = "Fläche";
            // 
            // tbArea
            // 
            this.tbArea.Enabled = false;
            this.tbArea.Location = new System.Drawing.Point(12, 288);
            this.tbArea.Name = "tbArea";
            this.tbArea.Size = new System.Drawing.Size(200, 20);
            this.tbArea.TabIndex = 14;
            // 
            // btRandomize
            // 
            this.btRandomize.Location = new System.Drawing.Point(341, 300);
            this.btRandomize.Name = "btRandomize";
            this.btRandomize.Size = new System.Drawing.Size(120, 23);
            this.btRandomize.TabIndex = 15;
            this.btRandomize.Text = "Randomize this image";
            this.btRandomize.UseVisualStyleBackColor = true;
            this.btRandomize.Click += new System.EventHandler(this.Randomize_Click);
            // 
            // btAddImage
            // 
            this.btAddImage.Location = new System.Drawing.Point(215, 300);
            this.btAddImage.Name = "btAddImage";
            this.btAddImage.Size = new System.Drawing.Size(120, 23);
            this.btAddImage.TabIndex = 16;
            this.btAddImage.Text = "Overlay image";
            this.btAddImage.UseVisualStyleBackColor = true;
            this.btAddImage.Click += new System.EventHandler(this.AddImage_Click);
            // 
            // ShapeEditor
            // 
            this.AcceptButton = this.btnOK;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(554, 335);
            this.Controls.Add(this.btAddImage);
            this.Controls.Add(this.btRandomize);
            this.Controls.Add(this.tbArea);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.cbResizeable);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.cbRotateable);
            this.Controls.Add(this.pointPanel);
            this.Controls.Add(this.tbCenterPoint);
            this.Controls.Add(this.numericRotation);
            this.Controls.Add(this.cbMoveable);
            this.Controls.Add(this.btnOK);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.Name = "ShapeEditor";
            this.ShowIcon = false;
            this.Text = "ShapeEditor";
            this.groupBox1.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.numericRotation)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Button btnOK;
        private System.Windows.Forms.Button btnChangeFillColor;
        private System.Windows.Forms.Button btnChangeBorderColor;
        private System.Windows.Forms.Panel panelFillColor;
        private System.Windows.Forms.Panel panelBorderColor;
        private System.Windows.Forms.CheckBox cbMoveable;
        private System.Windows.Forms.NumericUpDown numericRotation;
        private System.Windows.Forms.TextBox tbCenterPoint;
        private System.Windows.Forms.Panel pointPanel;
        private System.Windows.Forms.CheckBox cbRotateable;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.CheckBox cbResizeable;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox tbArea;
        private System.Windows.Forms.Button btRandomize;
        private System.Windows.Forms.Button btAddImage;

    }
}